# this defines the base environment to BUILD a11y testing binders
# across different development versions.
name: a11y

channels:
  - conda-forge
  - nodefaults

dependencies:
  # baseline runtimes
  - nodejs >=12,<15,!=13.*
  - python >=3.7,<3.10
  - yarn <2
  # jupyterlab itself (though it will be likely removed)
  - jupyter_server
  - jupyterlab >=3.0.9
  - jupyterlab_server >=2.3,<2.4
  - nbclassic
  # jupyterlab build
  - jupyter-packaging
  - pip
  - twine
  - wheel
  # jupyterlab demo
  - matplotlib-base
  - numpy
  - vega_datasets
  - xeus-python
  # jupyterlab docs
  - recommonmark
  - sphinx
  - sphinx_rtd_theme
  - sphinx-copybutton
  - sphinx-sitemap
  # this repo's tools
  - black
  - doit
  - flake8
  - git
  - pyyaml
  - toml
