# this defines the base environment to BUILD a11y testing binders
# across different development versions.
name: a11y
channels:
  - conda-forge
  - nodefaults
dependencies:
  - black
  - doit
  - git
  - jupyter_server
  - jupyter-packaging
  - jupyterlab >=3.0.9
  - jupyterlab_server >=2.3,<2.4
  - matplotlib-base
  - nbclassic
  - nodejs >=12,<15,!=13.*
  - numpy
  - pip
  - python >=3.7,<3.10
  - pyyaml
  - twine
  - vega_datasets
  - wheel
  - xeus-python
  - yarn <2
